import logging
import mmap
import os
import struct
import threading
import time
from collections.abc import Sequence

from services.log_file_store import _safe_name

"""
services/fast_path.py
---------------------
High-performance random access to raw logs using mmap.

This service allows the sidecar to fetch any log line by its ``line_id`` in O(1) time
without reading the entire file. It uses the companion ``.index`` files generated by
DiskLogStore to find the exact byte offsets of each line.
"""


logger = logging.getLogger(__name__)


class MappedSource:
    """
    Encapsulates mmap objects for a single source's log and index files.
    """

    __slots__ = (
        "log_path",
        "idx_path",
        "_log_mmap",
        "_idx_mmap",
        "_log_f",
        "_idx_f",
        "lock",
        "_last_check",
        "_last_log_size",
        "_last_idx_size",
    )

    def __init__(self, log_path: str, idx_path: str):
        self.log_path = log_path
        self.idx_path = idx_path
        self.lock = threading.Lock()
        self._log_mmap = None
        self._idx_mmap = None
        self._log_f = None
        self._idx_f = None
        self._last_check = 0.0
        self._last_log_size = 0
        self._last_idx_size = 0

    def _ensure_mapped(self):
        """Lazy initialization of mmap objects with size caching."""
        now = time.time()
        # Optimization: Only stat the files frequently if not mapped or if size changed
        if self._log_mmap is not None and self._idx_mmap is not None:
            if now - self._last_check < 0.1:  # 100ms debounce
                return

            self._last_check = now
            log_size = os.path.getsize(self.log_path)
            idx_size = os.path.getsize(self.idx_path)

            if log_size == self._last_log_size and idx_size == self._last_idx_size:
                return

            # Check if file sizes changed (appended)
            if log_size > self._log_mmap.size() or idx_size > self._idx_mmap.size():
                self.close()
            else:
                self._last_log_size = log_size
                self._last_idx_size = idx_size
                return

        try:
            self._last_check = now
            self._last_log_size = os.path.getsize(self.log_path)
            self._last_idx_size = os.path.getsize(self.idx_path)

            if self._last_log_size == 0 or self._last_idx_size < 8:
                return

            self._log_f = open(self.log_path, "rb")  # noqa: SIM115
            self._idx_f = open(self.idx_path, "rb")  # noqa: SIM115

            # ACCESS_READ for shared memory safety
            self._log_mmap = mmap.mmap(self._log_f.fileno(), 0, access=mmap.ACCESS_READ)
            self._idx_mmap = mmap.mmap(self._idx_f.fileno(), 0, access=mmap.ACCESS_READ)
        except Exception as e:
            logger.error("[FastPath] Mapping failed for %s: %s", self.log_path, e)
            self.close()

    def get_line(self, line_id: int) -> str | None:
        with self.lock:
            self._ensure_mapped()
            if not self._idx_mmap or not self._log_mmap:
                return None

            # Each entry in index is 8 bytes.
            # We need entry line_id (start) and line_id + 1 (end).
            start_pos = line_id * 8
            end_pos = (line_id + 1) * 8

            if end_pos > self._idx_mmap.size():
                return None

            try:
                offsets = self._idx_mmap[start_pos : end_pos + 8]  # read 16 bytes for start and end
                if len(offsets) < 16:
                    return None

                start_offset = struct.unpack("<Q", offsets[0:8])[0]
                end_offset = struct.unpack("<Q", offsets[8:16])[0]

                line_bytes = self._log_mmap[start_offset:end_offset]
                return line_bytes.decode("utf-8", errors="replace").rstrip("\n")
            except Exception as e:
                logger.error(
                    "[FastPath] Error reading line %d from %s: %s", line_id, self.log_path, e
                )
                return None

    def close(self):
        if self._log_mmap:
            self._log_mmap.close()
            self._log_mmap = None
        if self._idx_mmap:
            self._idx_mmap.close()
            self._idx_mmap = None
        if self._log_f:
            self._log_f.close()
            self._log_f = None
        if self._idx_f:
            self._idx_f.close()
            self._idx_f = None


class FastPathService:
    """
    Singleton service providing O(1) access to raw log text.
    """

    def __init__(self, storage_dir: str, log_store=None):
        self.storage_dir = storage_dir
        self.log_store = log_store  # Link to DiskLogStore for locking
        self._sources: dict[str, MappedSource] = {}
        self._lock = threading.Lock()
        self.hydrate_misses = 0  # Health metric

    def get_line(self, source_id: str, line_id: int) -> str | None:
        source = self._get_source(source_id)
        if not source:
            return None

        # BUG-002 Resolution: Removed DiskLogStore lock. 
        # mmap handles concurrent reads safely, and we only read lines 
        # that were already committed to the DB, so they must exist on disk.
        res = source.get_line(line_id)

        if res is None:
            self.hydrate_misses += 1
        return res

    def get_lines(self, source_id: str, line_ids: Sequence[int]) -> list[str | None]:
        source = self._get_source(source_id)
        if not source:
            return [None] * len(line_ids)

        results = []
        for lid in line_ids:
            res = source.get_line(lid)
            if res is None:
                self.hydrate_misses += 1
            results.append(res)

        return results

    def _get_source(self, source_id: str) -> MappedSource | None:
        with self._lock:
            if source_id not in self._sources:
                # Need to match the filename logic in DiskLogStore
                pass # 
                safe = _safe_name(source_id)
                log_path = os.path.join(self.storage_dir, f"{safe}.log")
                idx_path = os.path.join(self.storage_dir, f"{safe}.index")

                if not os.path.exists(log_path) or not os.path.exists(idx_path):
                    logger.error("[FastPath] Files missing: %s or %s", log_path, idx_path)
                    return None

                logger.info("[FastPath] Mapping source %s: %s", source_id, log_path)
                self._sources[source_id] = MappedSource(log_path, idx_path)
            return self._sources[source_id]

    def close_all(self):
        with self._lock:
            for src in self._sources.values():
                src.close()
            self._sources.clear()
