"""
services/fast_path.py
---------------------
High-performance random access to raw logs using mmap.

This service allows the sidecar to fetch any log line by its ``line_id`` in O(1) time
without reading the entire file. It uses the companion ``.index`` files generated by 
DiskLogStore to find the exact byte offsets of each line.
"""

import logging
import mmap
import os
import struct
import threading
from collections.abc import Sequence

logger = logging.getLogger(__name__)

class MappedSource:
    """
    Encapsulates mmap objects for a single source's log and index files.
    """
    __slots__ = ("log_path", "idx_path", "_log_mmap", "_idx_mmap", "_log_f", "_idx_f", "lock")

    def __init__(self, log_path: str, idx_path: str):
        self.log_path = log_path
        self.idx_path = idx_path
        self.lock = threading.Lock()
        self._log_mmap = None
        self._idx_mmap = None
        self._log_f = None
        self._idx_f = None

    def _ensure_mapped(self):
        """Lazy initialization of mmap objects."""
        if self._log_mmap is not None:
            # Check if file size changed (appended)
            if os.path.getsize(self.log_path) > self._log_mmap.size():
                self.close()
            else:
                return

        try:
            log_size = os.path.getsize(self.log_path)
            idx_size = os.path.getsize(self.idx_path)
            if log_size == 0 or idx_size < 8:
                return

            self._log_f = open(self.log_path, "rb")  # noqa: SIM115
            self._idx_f = open(self.idx_path, "rb")  # noqa: SIM115
            
            # ACCESS_READ for shared memory safety
            self._log_mmap = mmap.mmap(self._log_f.fileno(), 0, access=mmap.ACCESS_READ)
            self._idx_mmap = mmap.mmap(self._idx_f.fileno(), 0, access=mmap.ACCESS_READ)
        except Exception as e:
            logger.error("[FastPath] Mapping failed for %s: %s", self.log_path, e)
            self.close()

    def get_line(self, line_id: int) -> str | None:
        with self.lock:
            self._ensure_mapped()
            if not self._idx_mmap or not self._log_mmap:
                return None
            
            # Each entry in index is 8 bytes.
            # We need entry line_id (start) and line_id + 1 (end).
            start_pos = line_id * 8
            end_pos = (line_id + 1) * 8
            
            if end_pos > self._idx_mmap.size():
                return None
            
            try:
                offsets = self._idx_mmap[start_pos : end_pos + 8] # read 16 bytes for start and end
                if len(offsets) < 16:
                    return None
                
                start_offset = struct.unpack("<Q", offsets[0:8])[0]
                end_offset = struct.unpack("<Q", offsets[8:16])[0]
                
                line_bytes = self._log_mmap[start_offset:end_offset]
                return line_bytes.decode("utf-8", errors="replace").rstrip("\n")
            except Exception as e:
                logger.error("[FastPath] Error reading line %d from %s: %s", line_id, self.log_path, e)
                return None

    def close(self):
        if self._log_mmap:
            self._log_mmap.close()
            self._log_mmap = None
        if self._idx_mmap:
            self._idx_mmap.close()
            self._idx_mmap = None
        if self._log_f:
            self._log_f.close()
            self._log_f = None
        if self._idx_f:
            self._idx_f.close()
            self._idx_f = None

class FastPathService:
    """
    Singleton service providing O(1) access to raw log text.
    """
    def __init__(self, storage_dir: str):
        self.storage_dir = storage_dir
        self._sources: dict[str, MappedSource] = {}
        self._lock = threading.Lock()

    def get_line(self, source_id: str, line_id: int) -> str | None:
        source = self._get_source(source_id)
        if not source:
            return None
        return source.get_line(line_id)

    def get_lines(self, source_id: str, line_ids: Sequence[int]) -> list[str | None]:
        source = self._get_source(source_id)
        if not source:
            return [None] * len(line_ids)
        
        # Batching doesn't really help mmap much but we keep the API consistent
        return [source.get_line(lid) for lid in line_ids]

    def _get_source(self, source_id: str) -> MappedSource | None:
        with self._lock:
            if source_id not in self._sources:
                # Need to match the filename logic in DiskLogStore
                from services.log_file_store import _safe_name
                safe = _safe_name(source_id)
                log_path = os.path.join(self.storage_dir, f"{safe}.log")
                idx_path = os.path.join(self.storage_dir, f"{safe}.index")
                
                if not os.path.exists(log_path) or not os.path.exists(idx_path):
                    logger.error("[FastPath] Files missing: %s or %s", log_path, idx_path)
                    return None
                
                logger.info("[FastPath] Mapping source %s: %s", source_id, log_path)
                self._sources[source_id] = MappedSource(log_path, idx_path)
            return self._sources[source_id]

    def close_all(self):
        with self._lock:
            for src in self._sources.values():
                src.close()
            self._sources.clear()
