/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LogLensAiAPISchema =
  | JSONRPCRequest
  | JSONRPCResponse
  | LogFilter
  | GetLogsRequest
  | StartTailRequest
  | StartSSHTailRequest
  | IngestLogEntry
  | IngestLogsRequest
  | UpdateCommentRequest
  | GetWorkspaceSourcesRequest
  | ReadFileRequest
  | FusionSourceConfig
  | UpdateTemporalOffsetsRequest
  | GetTemporalOffsetsRequest
  | UpdateFusionConfigRequest
  | GetFusionConfigRequest
  | GetSampleLinesRequest
  | UpdateSourceParserRequest
  | GetFusedLogsRequest
  | GetAnomaliesRequest
  | GetLogDistributionRequest
  | GetMetadataFacetsRequest
  | SendAiMessageRequest
  | GetAiSessionsRequest
  | GetAiMessagesRequest
  | SaveMemoryRequest
  | SearchMemoryRequest
  | GetSettingsRequest
  | UpdateSettingsRequest;
export type Jsonrpc = string;
export type Method = string;
export type Jsonrpc1 = string;
export type Error = {
  [k: string]: unknown;
} | null;
export type Field = string;
export type Value = string;
export type Operator = string;
export type WorkspaceId = string;
export type Offset = number;
export type Limit = number;
export type Filters = LogFilter[] | null;
export type Query = string | null;
export type SortBy = string;
export type SortOrder = string;
export type StartTime = string | null;
export type EndTime = string | null;
export type Filepath = string;
export type WorkspaceId1 = string;
export type Host = string;
export type Port = number;
export type Username = string;
export type Password = string | null;
export type Filepath1 = string;
export type WorkspaceId2 = string;
export type WorkspaceId3 = string;
export type SourceId = string;
export type RawText = string;
export type Timestamp = string | null;
export type Level = string;
export type Message = string | null;
export type Logs = IngestLogEntry[];
export type LogId = number;
export type Comment = string;
export type WorkspaceId4 = string;
export type Filepath2 = string;
export type SourceId1 = string;
export type Enabled = boolean;
export type TzOffset = number;
export type CustomFormat = string | null;
export type ParserConfig = string | null;
export type WorkspaceId5 = string;
export type WorkspaceId6 = string;
export type WorkspaceId7 = string;
export type FusionId = string;
export type Sources = FusionSourceConfig[];
export type WorkspaceId8 = string;
export type FusionId1 = string;
export type WorkspaceId9 = string;
export type SourceId2 = string;
export type Limit1 = number;
export type WorkspaceId10 = string;
export type SourceId3 = string;
export type ParserConfig1 = string;
export type WorkspaceId11 = string;
export type FusionId2 = string;
export type Offset1 = number;
export type Limit2 = number;
export type Filters1 = LogFilter[] | null;
export type Query1 = string | null;
export type SortBy1 = string;
export type SortOrder1 = string;
export type StartTime1 = string | null;
export type EndTime1 = string | null;
export type WorkspaceId12 = string;
export type TimeRange = string | null;
export type WorkspaceId13 = string;
export type FusionId3 = string | null;
export type SourceIds = string[] | null;
export type Filters2 = LogFilter[] | null;
export type Query2 = string | null;
export type StartTime2 = string | null;
export type EndTime2 = string | null;
export type WorkspaceId14 = string;
export type WorkspaceId15 = string;
export type SessionId = string | null;
export type SessionName = string | null;
export type Message1 = string;
export type Model = string | null;
export type ContextLogs = number[] | null;
export type ProviderSessionId = string | null;
export type Reasoning = boolean | null;
export type WorkspaceId16 = string;
export type SessionId1 = string;
export type WorkspaceId17 = string;
export type IssueSignature = string;
export type Resolution = string;
export type WorkspaceId18 = string;
export type Query3 = string;
export type Limit3 = number;
export type WorkspaceId19 = string | null;
export type WorkspaceId20 = string | null;

export interface JSONRPCRequest {
  jsonrpc?: Jsonrpc;
  id?: unknown;
  method: Method;
  params?: Params;
  [k: string]: unknown;
}
export interface Params {
  [k: string]: unknown;
}
export interface JSONRPCResponse {
  jsonrpc?: Jsonrpc1;
  id?: unknown;
  result?: unknown;
  error?: Error;
  [k: string]: unknown;
}
export interface LogFilter {
  field: Field;
  value: Value;
  operator?: Operator;
  [k: string]: unknown;
}
export interface GetLogsRequest {
  workspace_id: WorkspaceId;
  offset?: Offset;
  limit?: Limit;
  filters?: Filters;
  query?: Query;
  sort_by?: SortBy;
  sort_order?: SortOrder;
  start_time?: StartTime;
  end_time?: EndTime;
  [k: string]: unknown;
}
export interface StartTailRequest {
  filepath: Filepath;
  workspace_id: WorkspaceId1;
  [k: string]: unknown;
}
export interface StartSSHTailRequest {
  host: Host;
  port?: Port;
  username: Username;
  password?: Password;
  filepath: Filepath1;
  workspace_id: WorkspaceId2;
  [k: string]: unknown;
}
export interface IngestLogEntry {
  workspace_id: WorkspaceId3;
  source_id?: SourceId;
  raw_text: RawText;
  timestamp?: Timestamp;
  level?: Level;
  message?: Message;
  [k: string]: unknown;
}
export interface IngestLogsRequest {
  logs: Logs;
  [k: string]: unknown;
}
export interface UpdateCommentRequest {
  log_id: LogId;
  comment: Comment;
  [k: string]: unknown;
}
export interface GetWorkspaceSourcesRequest {
  workspace_id: WorkspaceId4;
  [k: string]: unknown;
}
export interface ReadFileRequest {
  filepath: Filepath2;
  [k: string]: unknown;
}
export interface FusionSourceConfig {
  source_id: SourceId1;
  enabled?: Enabled;
  tz_offset?: TzOffset;
  custom_format?: CustomFormat;
  parser_config?: ParserConfig;
  [k: string]: unknown;
}
export interface UpdateTemporalOffsetsRequest {
  workspace_id: WorkspaceId5;
  offsets: Offsets;
  [k: string]: unknown;
}
export interface Offsets {
  [k: string]: number;
}
export interface GetTemporalOffsetsRequest {
  workspace_id: WorkspaceId6;
  [k: string]: unknown;
}
export interface UpdateFusionConfigRequest {
  workspace_id: WorkspaceId7;
  fusion_id?: FusionId;
  sources: Sources;
  [k: string]: unknown;
}
export interface GetFusionConfigRequest {
  workspace_id: WorkspaceId8;
  fusion_id?: FusionId1;
  [k: string]: unknown;
}
export interface GetSampleLinesRequest {
  workspace_id: WorkspaceId9;
  source_id: SourceId2;
  limit?: Limit1;
  [k: string]: unknown;
}
export interface UpdateSourceParserRequest {
  workspace_id: WorkspaceId10;
  source_id: SourceId3;
  parser_config: ParserConfig1;
  [k: string]: unknown;
}
export interface GetFusedLogsRequest {
  workspace_id: WorkspaceId11;
  fusion_id?: FusionId2;
  offset?: Offset1;
  limit?: Limit2;
  filters?: Filters1;
  query?: Query1;
  sort_by?: SortBy1;
  sort_order?: SortOrder1;
  start_time?: StartTime1;
  end_time?: EndTime1;
  [k: string]: unknown;
}
export interface GetAnomaliesRequest {
  workspace_id: WorkspaceId12;
  time_range?: TimeRange;
  [k: string]: unknown;
}
export interface GetLogDistributionRequest {
  workspace_id: WorkspaceId13;
  fusion_id?: FusionId3;
  source_ids?: SourceIds;
  filters?: Filters2;
  query?: Query2;
  start_time?: StartTime2;
  end_time?: EndTime2;
  [k: string]: unknown;
}
export interface GetMetadataFacetsRequest {
  workspace_id: WorkspaceId14;
  [k: string]: unknown;
}
export interface SendAiMessageRequest {
  workspace_id: WorkspaceId15;
  session_id?: SessionId;
  session_name?: SessionName;
  message: Message1;
  model?: Model;
  context_logs?: ContextLogs;
  provider_session_id?: ProviderSessionId;
  reasoning?: Reasoning;
  [k: string]: unknown;
}
export interface GetAiSessionsRequest {
  workspace_id: WorkspaceId16;
  [k: string]: unknown;
}
export interface GetAiMessagesRequest {
  session_id: SessionId1;
  [k: string]: unknown;
}
export interface SaveMemoryRequest {
  workspace_id: WorkspaceId17;
  issue_signature: IssueSignature;
  resolution: Resolution;
  [k: string]: unknown;
}
export interface SearchMemoryRequest {
  workspace_id: WorkspaceId18;
  query: Query3;
  limit?: Limit3;
  [k: string]: unknown;
}
export interface GetSettingsRequest {
  workspace_id?: WorkspaceId19;
  [k: string]: unknown;
}
export interface UpdateSettingsRequest {
  settings: Settings;
  workspace_id?: WorkspaceId20;
  [k: string]: unknown;
}
export interface Settings {
  [k: string]: unknown;
}
